-- colors/colorscheme.lua
vim.o.termguicolors = true

local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
	Bold = { fg = "#FFFFFF", bold = true },
	Boolean = { link = "Default" },
	Character = { link = "Popout" },
	ColorColumn = { link = "Subtle" },
	Comment = { link = "Faded" },
	Conceal = {},
	Conditional = { link = "Salient" },
	ConflictMarkerBegin = { bg = "#455254" },
	ConflictMarkerCommonAncestorsHunk = { bg = "#504950" },
	ConflictMarkerEnd = { bg = "#3D495C" },
	ConflictMarkerOurs = { bg = "#455254" },
	ConflictMarkerTheirs = { bg = "#3D495C" },
	Constant = { link = "Strong" },
	Critical = { fg = "#2B303B", bg = "#BE6069" },
	CriticalI = { fg = "#BE6069" },
	Cursor = { fg = "#2B303B", bg = "#ECEFF4" },
	CursorColumn = { link = "Subtle" },
	CursorLine = { bg = "#2F3541", sp = "none" },
	CursorLineNr = { fg = "#59657D", bg = "#2F3541" },
	DapUIBreakpointsCurrentLine = { fg = "#9FBB86", bold = true },
	DapUIBreakpointsInfo = { link = "Success" },
	DapUIBreakpointsLine = { link = "DapUILineNumber" },
	DapUIBreakpointsPath = { link = "Salient" },
	DapUIDecoration = { link = "Faded" },
	DapUIFloatBorder = { fg = "#2F3541", bg = "#2F3541" },
	DapUIFrameName = { link = "DapUINormal" },
	DapUILineNumber = { link = "Faded" },
	DapUIModifiedValue = { link = "Popout" },
	DapUINormal = { link = "Default" },
	DapUINormalFloat = { link = "Subtle" },
	DapUINormalNC = { link = "Default" },
	DapUIPlayPause = { link = "Success" },
	DapUIPlayPauseNC = { link = "Success" },
	DapUIRestart = { link = "Success" },
	DapUIRestartNC = {},
	DapUIScope = { link = "Salient" },
	DapUISource = { link = "Salient" },
	DapUIStepBack = { link = "DapUINormal" },
	DapUIStepBackNC = { link = "DapUINormal" },
	DapUIStepInto = { link = "DapUINormal" },
	DapUIStepIntoNC = { link = "DapUINormal" },
	DapUIStepOut = { link = "DapUINormal" },
	DapUIStepOutNC = { link = "DapUINormal" },
	DapUIStepOver = { link = "DapUINormal" },
	DapUIStepOverNC = { link = "DapUINormal" },
	DapUIStop = { link = "CriticalI" },
	DapUIStopNC = { link = "CriticalI" },
	DapUIStoppedThread = { link = "Faded" },
	DapUIThread = { link = "Success" },
	DapUIType = { link = "Salient" },
	DapUIUnavailable = { link = "Faded" },
	DapUIUnavailableNC = { link = "Faded" },
	DapUIValue = { link = "DapUINormal" },
	DapUIVariable = { fg = "#ECEFF4", bold = true },
	DapUIWatchesEmpty = { link = "CriticalI" },
	DapUIWatchesError = { link = "CriticalI" },
	DapUIWatchesValue = { link = "Salient" },
	DapUIWinSelect = { link = "Salient" },
	Default = { fg = "#ECEFF4" },
	DefaultI = { fg = "#2B303B", bg = "#ECEFF4" },
	Define = { link = "Salient" },
	Delimiter = { link = "Default" },
	DiagnosticError = { link = "CriticalI" },
	DiagnosticFloatingError = { link = "Default" },
	DiagnosticFloatingHint = { link = "Default" },
	DiagnosticFloatingInfo = { link = "Default" },
	DiagnosticFloatingWarn = { link = "Default" },
	DiagnosticHint = { link = "Salient" },
	DiagnosticInfo = { link = "Salient" },
	DiagnosticSignError = { link = "CriticalI" },
	DiagnosticSignHint = { link = "Salient" },
	DiagnosticSignInfo = { link = "Salient" },
	DiagnosticSignWarn = { link = "Popout" },
	DiagnosticUnderlineError = { fg = "none", sp = "#BE6069", undercurl = true },
	DiagnosticUnderlineHint = { fg = "none", sp = "#BE6069", undercurl = true },
	DiagnosticUnderlineInfo = { fg = "none", sp = "#BE6069", undercurl = true },
	DiagnosticUnderlineWarn = { fg = "none", sp = "#BE6069", undercurl = true },
	DiagnosticVirtualTextError = { link = "CriticalI" },
	DiagnosticVirtualTextInfo = { link = "Salient" },
	DiagnosticVirtualTextWarn = { link = "Popout" },
	DiagnosticWarn = { link = "Popout" },
	DiagnosticsVirtualTextHint = { link = "Salient" },
	DiffAdd = { bg = "#434E51" },
	DiffChange = { bg = "#3E4C60" },
	DiffDelete = { bg = "#504653" },
	DiffText = { bg = "#4D5D75" },
	Directory = { link = "Salient" },
	EndOfBuffer = { link = "None" },
	Error = { link = "Critical" },
	ErrorMsg = { link = "CriticalI" },
	Exception = { link = "Salient" },
	Faded = { fg = "#59657D" },
	FadedI = { fg = "#2B303B", bg = "#59657D" },
	Float = { link = "Popout" },
	FloatBorder = { fg = "#2F3541", bg = "#2F3541" },
	FoldColumn = { fg = "#59657D", bg = "#2B303B" },
	Folded = { fg = "#59657D" },
	Function = { bold = true },
	GitSignsAdd = { link = "Success" },
	GitSignsAddNr = { fg = "#707E99", bg = "#434E51" },
	GitSignsChange = { link = "Salient" },
	GitSignsChangeDelete = { link = "Popout" },
	GitSignsChangeDeleteNr = { fg = "#707E99", bg = "#4A464E" },
	GitSignsChangeNr = { fg = "#707E99", bg = "#3B4659" },
	GitSignsCurrentLineBlame = { fg = "#4C566B" },
	GitSignsDelete = { link = "CriticalI" },
	GitSignsDeleteNr = { fg = "#707E99", bg = "#433F4B" },
	Highlight = { bg = "#394151" },
	Identifier = { link = "Default" },
	IncSearch = { link = "PopoutI" },
	Include = { link = "Salient" },
	IndentBlanklineIndent = { link = "None" },
	IndentBlanklineIndentContext = { fg = "#394151" },
	Italic = { fg = "#59657D" },
	Keyword = { link = "Salient" },
	Label = { link = "Salient" },
	LineNr = { link = "Faded" },
	LspReferenceRead = { link = "Highlight" },
	LspReferenceText = { link = "Highlight" },
	LspReferenceWrite = { link = "Highlight" },
	Macro = { link = "Define" },
	MatchParen = { link = "Strong" },
	ModeMsg = { link = "Normal" },
	MoreMsg = { link = "Salient" },
	NavicIcons = { link = "NavicText" },
	NavicSeparator = { link = "NavicText" },
	NavicText = { fg = "#ECEFF4", bg = "#394151" },
	NeogitNotificationError = { link = "CriticalI" },
	NeogitNotificationInfo = { link = "Salient" },
	NeogitNotificationWarning = { link = "Popout" },
	NonText = { link = "Default" },
	None = { fg = "#ECEFF4" },
	Normal = { fg = "#ECEFF4", bg = "#2B303B" },
	NormalFloat = { link = "Subtle" },
	NotifyDEBUGBody = { link = "Normal" },
	NotifyDEBUGBorder = { link = "Faded" },
	NotifyDEBUGIcon = { link = "Faded" },
	NotifyDEBUGTitle = { link = "Faded" },
	NotifyERRORBody = { link = "Normal" },
	NotifyERRORBorder = { link = "CriticalI" },
	NotifyERRORIcon = { link = "CriticalI" },
	NotifyERRORTitle = { link = "CriticalI" },
	NotifyINFOBody = { link = "Normal" },
	NotifyINFOBorder = { link = "Salient" },
	NotifyINFOIcon = { link = "Salient" },
	NotifyINFOTitle = { link = "Salient" },
	NotifyTRACEBody = { link = "Normal" },
	NotifyTRACEBorder = { link = "Faded" },
	NotifyTRACEIcon = { link = "Faded" },
	NotifyTRACETitle = { link = "Faded" },
	NotifyWARNBody = { link = "Normal" },
	NotifyWARNBorder = { link = "Popout" },
	NotifyWARNIcon = { link = "Popout" },
	NotifyWARNTitle = { link = "Popout" },
	Number = { fg = "#BE6069" },
	Operator = { link = "Default" },
	OrgAgendaDeadline = { link = "Popout" },
	OrgAgendaScheduled = { link = "Normal" },
	OrgAgendaScheduledPast = { link = "PopoutI" },
	OrgTSHeadlineLevel1 = { link = "Bold" },
	OrgTSHeadlineLevel2 = { link = "Normal" },
	OrgTSHeadlineLevel3 = { link = "Normal" },
	OrgTSHeadlineLevel4 = { link = "Normal" },
	OrgTSHeadlineLevel5 = { link = "Normal" },
	OrgTSHeadlineLevel6 = { link = "Normal" },
	OrgTSHeadlineLevel7 = { link = "Normal" },
	OrgTSHeadlineLevel8 = { link = "Normal" },
	Pmenu = { bg = "#2F3541" },
	PmenuSbar = { link = "Subtle" },
	PmenuSel = { link = "FadedI" },
	PmenuThumb = { link = "SalientI" },
	Popout = { fg = "#D18771" },
	PopoutI = { fg = "#2B303B", bg = "#D18771" },
	PreCondit = { link = "PreProc" },
	PreProc = { link = "Popout" },
	Question = { link = "Normal" },
	Repeat = { link = "Salient" },
	Salient = { fg = "#81A1C1" },
	SalientI = { fg = "#2B303B", bg = "#81A1C1" },
	Search = { link = "PopoutI" },
	SignColumn = { link = "Normal" },
	Special = { link = "Default" },
	SpecialChar = { link = "Popout" },
	SpecialComment = { link = "Faded" },
	SpecialKey = { link = "Faded" },
	SpellBad = { sp = "#BE6069", undercurl = true },
	SpellCap = { sp = "#D18771", undercurl = true },
	SpellLocal = { sp = "#ECEFF4", undercurl = true },
	SpellRare = { sp = "#ECEFF4", undercurl = true },
	Statement = { link = "Default" },
	StatusComponentBase = { fg = "#ECEFF4", bg = "#394151" },
	StatusComponentDefault = { link = "StatusComponentBase" },
	StatusComponentFilename = { fg = "#FFFFFF", bg = "#394151" },
	StatusComponentInactive = { fg = "#59657D", bg = "#394151" },
	StatusComponentPosition = { fg = "#2B303B", bg = "#59657D" },
	StatusComponentVimBlock = { link = "StatusComponentVimVisual" },
	StatusComponentVimCommand = { link = "StatusComponentVimInsert" },
	StatusComponentVimEnter = { link = "StatusComponentVimNormal" },
	StatusComponentVimInactive = { link = "StatusComponentBase" },
	StatusComponentVimInsert = { fg = "#ECEFF4", bg = "#D18771" },
	StatusComponentVimLines = { link = "StatusComponentVimVisual" },
	StatusComponentVimMore = { link = "StatusComponentVimNormal" },
	StatusComponentVimNormal = { fg = "#ECEFF4", bg = "#59657D" },
	StatusComponentVimOp = { fg = "#ECEFF4", bg = "#59657D" },
	StatusComponentVimReplace = { link = "StatusComponentVimInsert" },
	StatusComponentVimSelect = { link = "StatusComponentVimVisual" },
	StatusComponentVimShell = { link = "StatusComponentVimNormal" },
	StatusComponentVimTerm = { link = "StatusComponentVimNormal" },
	StatusComponentVimVReplace = { link = "StatusComponentVimReplace" },
	StatusComponentVimVisual = { bg = "#9FBB86" },
	StorageClass = { link = "Strong" },
	String = { fg = "#BE6069" },
	Strong = { fg = "#FFFFFF", bold = true },
	StrongI = { fg = "#2B303B", bg = "#FFFFFF" },
	Structure = { link = "Salient" },
	Subtle = { bg = "#2F3541" },
	SubtleI = { fg = "#394151" },
	Success = { fg = "#9FBB86" },
	SuccessI = { fg = "#2B303B", bg = "#9FBB86" },
	TSDanger = { link = "Critical" },
	TSNote = {},
	TSTag = { link = "Bold" },
	TSTagDelimiter = { link = "Faded" },
	TSWarning = { link = "PopoutI" },
	TabLine = { link = "Faded" },
	TabLineFill = { link = "None" },
	TabLineSel = { link = "Normal" },
	Tag = { link = "Bold" },
	TelescopeBorder = { fg = "#2F3541", bg = "#2F3541" },
	TelescopeMatching = { link = "Salient" },
	TelescopeMultiSelection = { link = "Highlight" },
	TelescopeNormal = { fg = "#ECEFF4", bg = "#2F3541" },
	TelescopePreviewBorder = { link = "TelescopeBorder" },
	TelescopePrompt = { link = "TelescopeNormal" },
	TelescopePromptBorder = { link = "TelescopeBorder" },
	TelescopePromptPrefix = { link = "Salient" },
	TelescopeResultsBorder = { link = "TelescopeBorder" },
	TelescopeSelection = { link = "Highlight" },
	TelescopeSelectionCaret = { link = "Salient" },
	Title = { link = "Bold" },
	Todo = { link = "Strong" },
	Type = { link = "Salient" },
	Typedef = { link = "Salient" },
	Undercurl = { undercurl = true },
	Underline = { underline = true },
	VertSplit = { link = "None" },
	Visual = { link = "Highlight" },
	VisualNOS = { link = "Highlight" },
	WarningMsg = { link = "PopoutI" },
	WildMenu = { link = "SalientI" },
	["@attribute"] = { link = "Faded" },
	["@property"] = { link = "Default" },
	["@tag.attribute"] = { link = "Default" },
	["@tag.delimiter"] = { link = "Faded" },
	fugitiveCount = { link = "Popout" },
	fugitiveHash = { link = "Default" },
	fugitiveHeader = {},
	fugitiveHeading = { fg = "#81A1C1", bold = true },
	fugitiveHelpHeader = { link = "fugitiveHeader" },
	fugitiveInstruction = { link = "Salient" },
	fugitiveModifier = { link = "Salient" },
	fugitiveStagedHeading = { link = "fugitiveHeading" },
	fugitiveStagedModifier = { link = "Salient" },
	fugitiveStop = { link = "Strong" },
	fugitiveSymbolicRef = { link = "Strong" },
	fugitiveUnstagedHeading = { link = "fugitiveHeading" },
	fugitiveUnstagedModifier = { link = "Salient" },
	fugitiveUntrackedHeading = { link = "fugitiveHeading" },
	fugitiveUntrackedModifier = { link = "Salient" },
	iCursor = { link = "Cursor" },
	netrwClassify = { link = "Normal" },
	netrwExe = { link = "CriticalI" },
	netrwMarkFile = {},
	netrwSymlink = { link = "Popout" },
	netrwTreeBar = { link = "Faded" },
	-- PATCH_CLOSE
	-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd "highlight clear"
vim.cmd "set t_Co=256"
if os.getenv "TERM" == "xterm-kitty" then
	vim.cmd "let &t_ut=''"
end
vim.o.background = "dark"
vim.cmd "let g:colors_name='nano_dark'"

-- apply highlight groups
for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end

-- some fixes for unwanted colors in the StatusLine
-- and underline in diff on cursorline
vim.cmd [[
		hi! StatusLine cterm=NONE gui=NONE
		hi! StatusLineNC cterm=NONE gui=NONE
		hi! link StatusLine None
    hi CursorLine ctermfg=2b303b
]]

require "nano.terminal" "dark"
